/*
@codekit-prepend "foundation/jquery.placeholder.js"
@codekit-prepend "foundation/jquery.foundation.alerts.js"
@codekit-prepend "foundation/jquery.foundation.accordion.js"
@codekit-prepend "foundation/jquery.foundation.buttons.js"
@codekit-prepend "foundation/jquery.foundation.tooltips.js"
@codekit-prepend "foundation/jquery.foundation.forms.js"
@codekit-prepend "foundation/jquery.foundation.tabs.js"
@codekit-prepend "foundation/jquery.foundation.navigation.js"
@codekit-prepend "foundation/jquery.foundation.reveal.js"
@codekit-prepend "foundation/jquery.foundation.orbit.js"
@codekit-prepend "foundation/app.js"
@codekit-prepend "client/jquery.isotope.js"
@codekit-prepend "client/jquery.flexslider.js"
@codekit-prepend "client/app.js"
*/
