/*
@codekit-prepend "vendor/jquery.js"
@codekit-prepend "vendor/zepto.js"
@codekit-prepend "vendor/custom.modernizr.js"
@codekit-prepend "foundation/foundation.js"
@codekit-prepend "foundation/foundation.alerts.js"
@codekit-prepend "foundation/foundation.clearing.js"
@codekit-prepend "foundation/foundation.cookie.js"
@codekit-prepend "foundation/foundation.dropdown.js"
@codekit-prepend "foundation/foundation.forms.js"
@codekit-prepend "foundation/foundation.joyride.js"
@codekit-prepend "foundation/foundation.magellan.js"
@codekit-prepend "foundation/foundation.orbit.js"
@codekit-prepend "foundation/foundation.placeholder.js"
@codekit-prepend "foundation/foundation.reveal.js"
@codekit-prepend "foundation/foundation.section.js"
@codekit-prepend "foundation/foundation.tooltips.js"
@codekit-prepend "foundation/foundation.topbar.js"
@codekit-prepend "client/jquery.isotope.js"
@codekit-prepend "client/jquery.flexslider.js"
@codekit-prepend "client/jquery.twitter.js"
@codekit-prepend "client/app.js"
*/